#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
# Consistency Audit Script for PR #351 Follow-up
# ═══════════════════════════════════════════════════════════════════════════

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPORT_FILE="${PROJECT_ROOT}/docs/reports/PR351_CONSISTENCY_AUDIT.md"
PRIMARY_CONFIG="${PROJECT_ROOT}/machinenativeops.yaml"

echo "# PR #351 Consistency Audit Report" > "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"
echo "**Date**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> "${REPORT_FILE}"
echo "**Generated By**: Consistency Audit Script" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

# ═══════════════════════════════════════════════════════════════════════════
# 1. Policy Reference Consistency Check
# ═══════════════════════════════════════════════════════════════════════════
echo "## 1. Policy Reference Consistency" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

echo "### Policy IDs Referenced Across Project" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"
echo "\`\`\`" >> "${REPORT_FILE}"
grep -r "SEC-PATH-001\|SEC-LOG-001\|SEC-CRYPTO-001" \
  --include="*.yaml" --include="*.yml" --include="*.md" --include="*.ts" \
  "${PROJECT_ROOT}" | grep -v "node_modules" | grep -v ".git" || echo "No policy references found"
echo "\`\`\`" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

# ═══════════════════════════════════════════════════════════════════════════
# 2. Naming Convention Consistency
# ═══════════════════════════════════════════════════════════════════════════
echo "## 2. Naming Convention Analysis" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

echo "### Error Classes" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"
echo "\`\`\`" >> "${REPORT_FILE}"
grep -r "class.*Error extends" --include="*.ts" "${PROJECT_ROOT}/core" | grep -v "node_modules" || echo "No error classes found"
echo "\`\`\`" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

echo "### Service Methods (Security-Related)" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"
echo "\`\`\`" >> "${REPORT_FILE}"
grep -r "resolveSafePath\|generateFileDigest\|SAFE_ROOT" --include="*.ts" "${PROJECT_ROOT}/core" | grep -v "node_modules" | head -20 || echo "No security methods found"
echo "\`\`\`" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

# ═══════════════════════════════════════════════════════════════════════════
# 3. Configuration Consistency
# ═══════════════════════════════════════════════════════════════════════════
echo "## 3. Configuration File Analysis" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

echo "### PR #351 References in Configs" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"
echo "\`\`\`" >> "${REPORT_FILE}"
grep -r "PR #351\|pr_351\|PR351" --include="*.yaml" --include="*.yml" "${PROJECT_ROOT}/config" "${PROJECT_ROOT}/governance" "${PRIMARY_CONFIG}" | grep -v "node_modules" || echo "No PR351 references in configs"
echo "\`\`\`" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

# ═══════════════════════════════════════════════════════════════════════════
# 4. Documentation Cross-References
# ═══════════════════════════════════════════════════════════════════════════
echo "## 4. Documentation Cross-Reference Check" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

echo "### PR #351 Documentation Files" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"
echo "\`\`\`" >> "${REPORT_FILE}"
find "${PROJECT_ROOT}/docs" -name "*PR351*" -o -name "*pr351*" 2>/dev/null || echo "No PR351 docs found"
echo "\`\`\`" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

echo "### DOCUMENTATION_INDEX.md References" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"
echo "\`\`\`" >> "${REPORT_FILE}"
grep "PR351\|PR #351" "${PROJECT_ROOT}/DOCUMENTATION_INDEX.md" || echo "No PR351 references in DOCUMENTATION_INDEX"
echo "\`\`\`" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

# ═══════════════════════════════════════════════════════════════════════════
# 5. Version Consistency
# ═══════════════════════════════════════════════════════════════════════════
echo "## 5. Version Information" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

echo "### Key Configuration Versions" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"
echo "\`\`\`" >> "${REPORT_FILE}"
echo "# machinenativeops.yaml" >> "${REPORT_FILE}"
grep "version:" "${PRIMARY_CONFIG}" | head -5 || echo "No version found"
echo "" >> "${REPORT_FILE}"
echo "# unified-config-index.yaml" >> "${REPORT_FILE}"
grep "version:" "${PROJECT_ROOT}/config/unified-config-index.yaml" | head -3 || echo "No version found"
echo "" >> "${REPORT_FILE}"
echo "# security-policies.yaml" >> "${REPORT_FILE}"
grep "version:" "${PROJECT_ROOT}/governance/10-policy/base-policies/security-policies.yaml" | head -3 || echo "No version found"
echo "\`\`\`" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

# ═══════════════════════════════════════════════════════════════════════════
# Summary
# ═══════════════════════════════════════════════════════════════════════════
echo "## Summary" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"
echo "This audit was conducted automatically to identify consistency issues" >> "${REPORT_FILE}"
echo "across the project following PR #351 security enhancements." >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"
echo "**Status**: Initial Audit Complete" >> "${REPORT_FILE}"
echo "**Next Steps**: Manual review and fixes based on findings" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

echo "Consistency audit report generated: ${REPORT_FILE}"
